2025-08-07 15:42:49.507 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-07 15:42:49.529 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kwh_to_won which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-07 15:42:49.543 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartthinq_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-07 15:42:49.555 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-07 15:42:49.570 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-07 15:42:49.585 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration bestin which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-07 15:42:49.601 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration icloud3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-07 15:43:55.189 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__('pkg_resources').declare_namespace(__name__)

2025-08-07 15:44:02.432 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('ble_monitor', '01K0ZZFTB18ARH0H2DRVTBK2GQ'): 9565.271787941, ('cpuspeed', '01K10090BFQPA8KF2K9YD2QG7R'): 9565.378879207, ('rpi_power', '01K0XWCM4YT6CBB0HXFVAG4JRC'): 9565.587659758, ('ios', '01K0ZYSVSQDX3Z5WCC4KA78J0X'): 9567.264680522, ('uptime', '01K0ZYTCTCKM1P639FTPNJFBJ8'): 9567.289753212, ('workday', '01K0ZYVXNEG2GWCQVC2RX60QX8'): 9567.797780156}
2025-08-07 15:44:31.138 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:44:38.533 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 15:44:49.267 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.jubang_gimcinaengjanggo_left_temperature for domain sensor with platform lg_thinq
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 663, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'kimchi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 666, in state
    numerical_value = float(value)
ValueError: could not convert string to float: 'kimchi'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1088, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1032, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.jubang_gimcinaengjanggo_left_temperature has device class 'None', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'kimchi' (<class 'str'>)
2025-08-07 15:44:49.363 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.jubang_gimcinaengjanggo_right_temperature for domain sensor with platform lg_thinq
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 663, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'kimchi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 666, in state
    numerical_value = float(value)
ValueError: could not convert string to float: 'kimchi'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1088, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1032, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.jubang_gimcinaengjanggo_right_temperature has device class 'None', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'kimchi' (<class 'str'>)
2025-08-07 15:44:49.426 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.jubang_gimcinaengjanggo_middle_temperature for domain sensor with platform lg_thinq
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 663, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'kimchi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 666, in state
    numerical_value = float(value)
ValueError: could not convert string to float: 'kimchi'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1088, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1032, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.jubang_gimcinaengjanggo_middle_temperature has device class 'None', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'kimchi' (<class 'str'>)
2025-08-07 15:44:49.478 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.jubang_gimcinaengjanggo_bottom_temperature for domain sensor with platform lg_thinq
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 668, in state
    numerical_value = float(value)  # type:ignore[arg-type]
ValueError: could not convert string to float: 'storage'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 676, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1002, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1382, in add_to_platform_finish
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1026, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1088, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1032, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.jubang_gimcinaengjanggo_bottom_temperature has device class 'None', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'storage' (<class 'str'>)
2025-08-07 15:44:49.519 ERROR (MainThread) [homeassistant.components.sensor] Platform lg_thinq does not generate unique IDs. ID dc4e8942ac9f34d85981b484492de8d1b372aef820c64de7740c08ce1c45a9e4_left_target_temperature already exists - ignoring sensor.jubang_gimcinaengjanggo_left_temperature
2025-08-07 15:44:49.520 ERROR (MainThread) [homeassistant.components.sensor] Platform lg_thinq does not generate unique IDs. ID dc4e8942ac9f34d85981b484492de8d1b372aef820c64de7740c08ce1c45a9e4_right_target_temperature already exists - ignoring sensor.jubang_gimcinaengjanggo_right_temperature
2025-08-07 15:44:49.521 ERROR (MainThread) [homeassistant.components.sensor] Platform lg_thinq does not generate unique IDs. ID dc4e8942ac9f34d85981b484492de8d1b372aef820c64de7740c08ce1c45a9e4_middle_target_temperature already exists - ignoring sensor.jubang_gimcinaengjanggo_middle_temperature
2025-08-07 15:44:49.524 ERROR (MainThread) [homeassistant.components.sensor] Platform lg_thinq does not generate unique IDs. ID dc4e8942ac9f34d85981b484492de8d1b372aef820c64de7740c08ce1c45a9e4_bottom_target_temperature already exists - ignoring sensor.jubang_gimcinaengjanggo_bottom_temperature
2025-08-07 15:45:15.030 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: {('icloud3', '01K100AHNS04N99B2R23VBPBCD'): 9651.430926943}
2025-08-07 15:45:31.945 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:45:38.819 WARNING (ImportExecutor_0) [py.warnings] /usr/local/lib/python3.13/site-packages/google/protobuf/runtime_version.py:98: UserWarning: Protobuf gencode version 5.29.0 is exactly one major version older than the runtime version 6.31.1 at ghome_foyer_api/api.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

2025-08-07 15:46:32.433 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:47:32.552 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:48:32.722 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:49:33.063 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:50:33.221 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:51:33.358 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:52:33.478 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:53:33.587 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:54:33.698 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:55:33.829 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:56:33.943 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:57:34.092 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:58:34.215 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 15:59:34.381 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:00:34.529 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:01:34.677 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:02:34.875 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:03:35.010 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:04:35.167 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:05:35.272 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:06:35.459 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:07:35.600 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:08:35.738 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:09:35.868 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:10:35.984 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:11:36.111 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:12:36.270 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:13:36.380 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:14:36.510 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:15:36.639 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:16:36.746 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:17:36.850 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:18:36.918 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:19:37.011 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:19:38.991 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:20:37.104 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:21:37.173 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:21:38.994 WARNING (SyncWorker_5) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:22:37.270 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:23:37.348 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:23:38.999 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:24:37.440 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:25:37.542 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:25:39.002 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:26:37.623 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:27:37.697 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:27:39.005 WARNING (SyncWorker_5) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:28:37.764 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:29:37.850 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:29:39.009 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:30:37.930 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:31:38.024 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:32:38.086 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:33:38.152 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:34:38.252 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:35:38.348 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:36:38.442 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:37:38.516 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:38:38.607 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:39:38.705 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:40:38.758 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:41:38.851 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:41:39.032 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:42:38.938 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:43:39.006 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:44:39.109 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:45:39.201 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:46:39.291 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:47:39.356 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:48:39.445 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:49:39.043 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:49:39.500 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:50:39.583 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:51:39.683 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:52:39.763 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:53:39.051 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:53:39.824 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:54:39.912 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:55:09.054 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:55:39.985 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:56:40.056 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:57:40.136 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:58:40.232 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 16:59:39.062 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 16:59:40.338 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:00:39.064 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 17:00:40.433 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:01:40.499 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:02:40.555 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:03:40.654 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:04:40.721 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:05:09.071 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 17:05:40.805 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:06:40.880 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:07:40.969 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:08:41.038 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:09:41.134 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:10:09.078 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 17:10:41.223 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:11:41.315 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:12:41.403 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:13:41.474 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:14:41.559 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:15:41.653 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:16:41.740 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:17:41.801 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:18:41.886 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:19:41.939 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:20:09.093 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 17:20:42.008 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:21:42.099 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:22:42.188 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:23:09.097 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 17:23:42.270 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:24:42.341 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:25:42.425 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:26:42.526 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:27:42.652 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:28:39.106 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 17:28:42.727 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:29:42.813 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:30:42.940 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:31:43.001 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:32:09.111 WARNING (SyncWorker_5) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 17:32:43.054 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:33:43.102 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:34:43.213 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:35:43.310 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:36:43.406 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:37:43.501 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:38:43.594 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:39:43.654 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:40:43.766 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:41:43.847 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:42:43.910 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:43:43.977 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:44:39.135 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 17:44:44.042 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:45:44.157 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:46:44.240 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:47:44.339 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:48:44.425 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:49:09.141 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 17:49:44.510 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:50:09.142 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 17:50:44.583 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:51:44.653 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:52:44.743 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:53:44.819 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:54:44.888 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:55:44.950 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:56:45.028 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:57:45.109 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:58:45.188 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 17:59:45.263 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:00:45.339 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:01:39.164 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:01:45.430 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:02:45.500 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:03:45.597 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:04:39.170 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:04:45.693 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:05:45.771 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:06:45.853 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:07:45.917 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:08:45.997 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:09:09.177 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:09:46.073 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:10:09.177 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:10:46.149 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:11:46.230 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:12:46.333 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:13:09.182 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:13:46.406 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:14:46.459 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:15:46.523 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:16:46.606 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:17:46.686 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:18:09.193 WARNING (SyncWorker_6) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:18:46.742 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:19:46.809 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:20:46.877 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:21:46.971 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:22:09.202 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:22:47.062 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:23:47.135 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:24:47.232 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:25:47.298 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:26:09.210 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:26:47.393 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:27:47.463 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:28:09.213 WARNING (SyncWorker_6) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:28:47.528 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:29:47.618 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:30:09.216 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:30:47.717 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:31:47.794 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:32:09.218 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:32:47.887 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:33:39.221 WARNING (SyncWorker_5) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:33:47.955 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:34:48.047 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:35:48.143 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:36:09.226 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:36:48.238 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:37:48.320 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:38:09.229 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:38:48.414 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:39:48.483 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:40:09.232 WARNING (SyncWorker_5) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:40:48.543 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:41:48.610 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:42:09.235 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:42:48.681 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:43:09.237 WARNING (SyncWorker_6) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:43:48.744 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:44:09.237 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:44:48.837 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:45:48.939 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:46:09.241 WARNING (SyncWorker_5) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:46:49.013 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:47:09.244 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:47:49.061 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:48:09.246 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:48:49.158 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:49:49.232 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:50:09.248 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:50:49.313 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:51:49.383 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:52:09.254 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:52:49.458 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:53:49.529 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:54:09.258 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:54:49.595 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:55:49.681 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:56:49.755 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:57:49.836 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:58:09.259 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 18:58:49.899 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 18:59:49.959 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:00:50.043 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:01:39.265 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:01:50.121 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:02:50.183 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:03:39.269 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:03:50.254 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:04:50.345 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:05:09.270 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:05:50.444 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:06:50.583 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:07:50.667 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:08:50.729 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:09:50.818 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:10:39.281 WARNING (SyncWorker_6) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:10:50.902 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:11:50.997 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:12:51.052 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:13:51.118 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:14:51.209 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:15:39.290 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:15:51.293 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:16:51.357 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:17:09.295 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:17:51.453 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:18:51.529 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:19:51.613 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:20:51.667 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:21:51.761 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:22:51.823 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:23:09.305 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:23:51.929 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:24:52.000 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:25:39.312 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:25:52.091 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:26:52.165 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:27:52.219 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:28:52.284 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:29:52.348 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:30:52.439 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:31:39.322 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:31:52.536 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:32:39.327 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:32:52.630 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:33:52.716 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:34:52.805 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:35:52.890 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:36:09.332 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:36:52.991 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:37:53.043 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:38:53.131 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:39:53.242 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:40:39.342 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:40:53.335 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:41:53.436 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:42:53.524 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:43:09.347 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:43:53.609 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:44:53.689 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:45:39.351 WARNING (SyncWorker_5) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:45:53.801 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:46:53.946 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:47:54.016 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:48:54.127 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:49:54.223 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:50:54.313 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:51:09.361 WARNING (SyncWorker_4) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:51:54.414 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:52:39.364 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:52:54.530 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:53:54.603 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:54:09.365 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:54:54.721 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:55:54.798 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:56:54.895 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:57:09.369 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:57:54.949 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:58:09.373 WARNING (SyncWorker_6) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 19:58:55.043 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 19:59:55.128 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:00:39.377 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:00:52.524 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.cpu_speed is taking over 10 seconds
2025-08-07 20:00:55.252 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:01:56.367 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:02:56.472 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:03:56.582 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:04:56.637 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:05:56.692 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:06:39.389 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:06:56.781 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:07:56.883 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:08:56.964 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:09:09.392 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:09:57.041 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:10:57.131 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:11:39.397 WARNING (SyncWorker_6) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:11:57.203 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:12:57.299 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:13:57.349 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:14:57.404 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:15:57.484 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:16:57.570 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:17:57.660 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:18:39.406 WARNING (SyncWorker_3) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:18:57.748 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:19:57.805 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:20:57.885 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:21:09.411 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:21:57.983 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:22:58.135 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:23:58.202 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:24:58.362 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:25:58.445 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:26:09.423 WARNING (SyncWorker_0) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:26:58.526 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:27:58.615 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:28:58.680 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:29:58.779 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:30:09.429 WARNING (SyncWorker_1) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:30:58.865 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:31:39.432 WARNING (SyncWorker_5) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:31:58.936 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:32:59.037 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:33:59.091 ERROR (SyncWorker_3) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:34:59.185 ERROR (SyncWorker_0) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:35:59.235 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:36:59.314 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:37:39.445 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:37:59.380 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:38:59.443 ERROR (SyncWorker_6) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:39:59.528 ERROR (SyncWorker_2) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:40:39.451 WARNING (SyncWorker_2) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2025-08-07 20:40:59.613 ERROR (SyncWorker_5) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:41:59.697 ERROR (SyncWorker_1) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:42:59.782 ERROR (SyncWorker_4) [homeassistant.components.influxdb] Cannot connect to InfluxDB due to 'HTTPSConnectionPool(host='a0d7b954-influxdb', port=8086): Max retries exceeded with url: /write?db=homeassistant (Caused by SSLError(SSLError(1, '[SSL] record layer failure (_ssl.c:1028)')))'. Please check that the provided connection details (host, port, etc.) are correct and that your InfluxDB server is running and accessible. Retrying in 60 seconds.
2025-08-07 20:43:09.459 WARNING (SyncWorker_6) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
